language: ruby
rvm:
  - 2.1.1
env:
  - RAILS_ENV=test
  - DB=postgresql
install:
  - bundle install
script:
  - rake db:create
  - rake db:migrate
before_script:
  - psql -c 'create database joga_facil_test;' -U postgres


